msgid ""
msgstr ""
"Project-Id-Version: Perrypedia\n"
"POT-Creation-Date: 2021-11-02 16:24+0100\n"
"PO-Revision-Date: 2021-11-02 16:27+0100\n"
"Last-Translator: Michael Detambel <info@michael-detambel.de>\n"
"Language-Team: Michael Detambel\n"
"Language: de_DE@formal\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 3.0\n"
"X-Poedit-Basepath: ..\n"
"Plural-Forms: nplurals=2; plural=(n != 1);\n"
"X-Poedit-SearchPath-0: .\n"

#: __init__.py:120
msgid "Downloads metadata and covers from Perrypedia (perrypedia.de)"
msgstr ""

#: __init__.py:584
msgid "Unexpected structure of field pp_id:"
msgstr ""

#: __init__.py:598
#, python-brace-format
msgid ""
"Malformed PPID: {0}. Parse title and authors fields for series and "
"issuenumber."
msgstr ""

#: __init__.py:649
msgid ""
"No metadata found with series code and/or issuenumber not found. Trying a "
"book title search."
msgstr ""

#: __init__.py:652
msgid "Series code and/or issuenumber not found. Trying a book title search."
msgstr ""

#: __init__.py:670
msgid "Next soup, Page title:"
msgstr ""

#: __init__.py:671
msgid "Next soup, url:"
msgstr ""

#: __init__.py:675
msgid "Result found with title search."
msgstr ""

#: __init__.py:685 __init__.py:1665
msgid "Trying to get series code and issuenumber from result."
msgstr ""

#: __init__.py:705
msgid ""
"No book found with text provided in title and authors fields - giving up."
msgstr ""

#: __init__.py:706
msgid ""
"Since metadata plugins cannot read book files for identification purposes, "
"you must provide appropiate data with manual input."
msgstr ""

#: __init__.py:708
msgid "Error: No metadata result. Abort."
msgstr ""

#: __init__.py:725
msgid "*** Enter download_cover()"
msgstr ""

#: __init__.py:754
msgid "No cached cover found, running identify."
msgstr ""

#: __init__.py:777
msgid "No luck to find cover with identify."
msgstr ""

#: __init__.py:795
msgid "Going to download cover from url"
msgstr ""

#: __init__.py:801
msgid "Have downloaded cover from"
msgstr ""

#: __init__.py:803
msgid "Failed to download cover from"
msgstr ""

#: __init__.py:900
msgid "Searching in title and authors field:"
msgstr ""

#: __init__.py:910
msgid "Match found for series code:"
msgstr ""

#: __init__.py:946
msgid "Series and/or issuenumber not found. Searching for subseries..."
msgstr ""

#: __init__.py:956
msgid "Searching subseries in title and authors:"
msgstr ""

#: __init__.py:964
msgid "Match found for "
msgstr ""

#: __init__.py:987
msgid "Subseries and/or subseries issuenumber not found."
msgstr ""

#: __init__.py:1062
msgid "API search with:"
msgstr ""

#: __init__.py:1063
msgid "GET url:"
msgstr ""

#: __init__.py:1068
msgid "Response list="
msgstr ""

#: __init__.py:1178
#, python-brace-format
msgid "{0} book source(s) found."
msgstr ""

#: __init__.py:1192
msgid "Page title:"
msgstr ""

#: __init__.py:1219
msgid "No possible book source found with"
msgstr ""

#: __init__.py:1227
msgid "Failed to download book metadata with title search. Giving up."
msgstr ""

#: __init__.py:1523
msgid "Found a relative cover page URL:"
msgstr ""

#: __init__.py:1552
msgid "Relative cover url:"
msgstr ""

#: __init__.py:1739
msgid "Key error while building authors field!"
msgstr ""

#: __init__.py:1745
msgid "Unknown"
msgstr ""

#: __init__.py:1793
msgid "Cover URLs cached:"
msgstr ""

#: __init__.py:2044
msgid "Found the relative cover page URL:"
msgstr ""

#: __init__.py:2047 __init__.py:2079
msgid "Effective URL:"
msgstr ""

#: __init__.py:2061
msgid "Cover page not found."
msgstr ""

#: __init__.py:2075
msgid "Found the relative cover URL:"
msgstr ""

#: __init__.py:2128
#, python-format
msgid "Cover test failed. Expected: '%s' found: "
msgstr ""
